# Generated by Django 2.2.2 on 2020-07-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_borrowtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='is_returned',
            field=models.BooleanField(default='True'),
        ),
    ]
