# Generated by Django 3.2.4 on 2021-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='no description', max_length=500),
        ),
    ]
