# Generated by Django 2.2.2 on 2020-07-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_borrowtransaction_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BorrowTransaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
