# Generated by Django 2.2.2 on 2020-08-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_borrowtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
    ]
