# Generated by Django 2.2.2 on 2020-08-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_auto_20200809_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='is_returned',
            field=models.BooleanField(default='True'),
        ),
    ]
